// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	startAuthentication: () => typedError<DeviceCodeResponse, string>(__TAURI_INVOKE("start_authentication")),
	pollAuthentication: (deviceCode: string) => typedError<MicrosoftToken, string>(__TAURI_INVOKE("poll_authentication", { deviceCode })),
	authenticate: (token: MicrosoftToken) => typedError<KableAccount, string>(__TAURI_INVOKE("authenticate", { token })),
	listAccounts: () => typedError<KableAccount[], string>(__TAURI_INVOKE("list_accounts")),
	addAccount: (account: KableAccount) => typedError<null, string>(__TAURI_INVOKE("add_account", { account })),
	removeAccount: (account: KableAccount) => typedError<KableAccount[], string>(__TAURI_INVOKE("remove_account", { account })),
	setActiveAccount: (account: KableAccount) => typedError<null, string>(__TAURI_INVOKE("set_active_account", { account })),
	getActiveAccount: () => typedError<{
	access_token: string,
	access_token_expires_at: string,
	/**  AES-encrypted refresh token for "persistent" accounts. */
	encrypted_refresh_token: string | null,
	avatar: string,
	eligible_for_free_trials: boolean,
	eligible_for_migration: boolean,
	franchise_inventory_id: string,
	has_multiple_profiles: boolean,
	in_forced_migration: boolean,
	legacy: boolean,
	license_product_ids: string[],
	/**  This is usually the same as the user's UUID but for correctness use the Minecraft Profile's ID! */
	local_id: string,
	minecraft_profile: KableMinecraftProfile,
	persistent: boolean,
	remote_id: string,
	type: string,
	user_properties: null[],
	username: string,
} | null, string>(__TAURI_INVOKE("get_active_account")),
	getIconTemplates: () => typedError<IconTemplate[], string>(__TAURI_INVOKE("get_icon_templates")),
	saveCustomIconTemplate: (template: IconTemplate) => typedError<string, string>(__TAURI_INVOKE("save_custom_icon_template", { template })),
	deleteCustomIconTemplate: (templateName: string) => typedError<null, string>(__TAURI_INVOKE("delete_custom_icon_template", { templateName })),
	openIconsDirectory: () => typedError<null, string>(__TAURI_INVOKE("open_icons_directory")),
	resolveImagePath: (key: string) => typedError<string, string>(__TAURI_INVOKE("resolve_image_path", { key })),
	getSettings: () => typedError<CategorizedLauncherSettings, string>(__TAURI_INVOKE("get_settings")),
	setSettings: (settings: CategorizedLauncherSettings) => typedError<null, string>(__TAURI_INVOKE("set_settings", { settings })),
	listSoundpacks: () => typedError<string[], string>(__TAURI_INVOKE("list_soundpacks")),
	getSoundpackMetadata: (pack: string) => typedError<SoundpackMetadata, string>(__TAURI_INVOKE("get_soundpack_metadata", { pack })),
	loadSoundpackFile: (pack: string, file: string) => typedError<number[], string>(__TAURI_INVOKE("load_soundpack_file", { pack, file })),
	importSoundpackZip: (path: string) => typedError<string, string>(__TAURI_INVOKE("import_soundpack_zip", { path })),
	getSoundsDirectoryPath: () => typedError<string, string>(__TAURI_INVOKE("get_sounds_directory_path")),
	openSoundsDirectory: () => typedError<null, string>(__TAURI_INVOKE("open_sounds_directory")),
	listCssThemes: () => typedError<Theme[], string>(__TAURI_INVOKE("list_css_themes")),
	loadCss: (theme: Theme) => typedError<string, string>(__TAURI_INVOKE("load_css", { theme })),
	saveCssTheme: (name: string, css: string) => typedError<string, string>(__TAURI_INVOKE("save_css_theme", { name, css })),
	deleteCssTheme: (name: string) => typedError<null, string>(__TAURI_INVOKE("delete_css_theme", { name })),
	openCssThemesDirectory: () => typedError<null, string>(__TAURI_INVOKE("open_css_themes_directory")),
	/**  Initialize Discord Rich Presence */
	initializeDiscordRpc: () => typedError<null, string>(__TAURI_INVOKE("initialize_discord_rpc")),
	/**  Enable or disable Discord Rich Presence globally */
	setDiscordEnabled: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_discord_enabled", { enabled })),
	/**  Set presence to "playing Minecraft" */
	setDiscordPlaying: (profile: KableProfile) => typedError<null, string>(__TAURI_INVOKE("set_discord_playing", { profile })),
	/**  Set presence to browsing a launcher section */
	setDiscordBrowsing: (section: string) => typedError<null, string>(__TAURI_INVOKE("set_discord_browsing", { section })),
	/**  Clear "playing" state (revert to idle / launcher state) */
	clearDiscordPlaying: () => typedError<null, string>(__TAURI_INVOKE("clear_discord_playing")),
	/**  Clear all Discord presence (hard reset) */
	clearDiscordPresence: () => typedError<null, string>(__TAURI_INVOKE("clear_discord_presence")),
	/**  Disconnect completely from Discord IPC */
	disconnectDiscord: () => typedError<null, string>(__TAURI_INVOKE("disconnect_discord")),
	launchGame: (profile: KableProfile) => typedError<LaunchResult, string>(__TAURI_INVOKE("launch_game", { profile })),
	autoDetectJava: () => typedError<string, string>(__TAURI_INVOKE("auto_detect_java")),
	getJavaPath: (javaPath: string | null) => typedError<string, string>(__TAURI_INVOKE("get_java_path", { javaPath })),
	browse: (profile: KableProfile, search: ProjectSearch, smartFilter: boolean, projectType: ProjectType) => typedError<ModrinthResults, string>(__TAURI_INVOKE("browse", { profile, search, smartFilter, projectType })),
	listProfileProjects: (profile: KableProfile, enabled: boolean) => typedError<Partial<{ [key in ProjectType]: KableProject[] }>, string>(__TAURI_INVOKE("list_profile_projects", { profile, enabled })),
	removeProject: (profile: KableProfile, kableProject: KableProject) => typedError<KableProject, string>(__TAURI_INVOKE("remove_project", { profile, kableProject })),
	addProjectToProfile: (profile: KableProfile, project: Project, versionId: string | null) => typedError<KableProject, string>(__TAURI_INVOKE("add_project_to_profile", { profile, project, versionId })),
	checkForUpdate: (kableProfile: KableProfile, kableProject: KableProject) => typedError<Project, string>(__TAURI_INVOKE("check_for_update", { kableProfile, kableProject })),
	checkForUpdates: (profile: KableProfile, projectType: ProjectType) => typedError<UpdateMap[], string>(__TAURI_INVOKE("check_for_updates", { profile, projectType })),
	updateProject: (profile: KableProfile, kableProject: KableProject) => typedError<KableProject, string>(__TAURI_INVOKE("update_project", { profile, kableProject })),
	updateAllProjects: (profile: KableProfile, projectType: ProjectType) => typedError<KableProject[], string>(__TAURI_INVOKE("update_all_projects", { profile, projectType })),
	getProfiles: () => typedError<KableProfile[], string>(__TAURI_INVOKE("get_profiles")),
	getProfile: (id: string) => typedError<KableProfile, string>(__TAURI_INVOKE("get_profile", { id })),
	createProfile: (versionId: string | null, baseProfile: {
	id: string,
	version: ProfileVersion,
	metadata: KableProfileMetadata,
	settings: KableProfileSettings,
} | null, exportedProfile: string | null, mrpack: string | null) => typedError<KableProfile, string>(__TAURI_INVOKE("create_profile", { versionId, baseProfile, exportedProfile, mrpack })),
	modifyProfile: (oldProfile: KableProfile, newProfile: KableProfile) => typedError<KableProfile, string>(__TAURI_INVOKE("modify_profile", { oldProfile, newProfile })),
	deleteProfile: (id: string) => typedError<null, string>(__TAURI_INVOKE("delete_profile", { id })),
	getVersions: () => typedError<Versions, string>(__TAURI_INVOKE("get_versions")),
	toggleProject: (profile: KableProfile, kableProject: KableProject) => typedError<KableProfile, string>(__TAURI_INVOKE("toggle_project", { profile, kableProject })),
	toggleFavorite: (profile: KableProfile) => typedError<KableProfile, string>(__TAURI_INVOKE("toggle_favorite", { profile })),
	isProjectEnabled: (profile: KableProfile, kableProject: KableProject) => typedError<boolean, string>(__TAURI_INVOKE("is_project_enabled", { profile, kableProject })),
	getSymlinks: () => typedError<Symlink[], string>(__TAURI_INVOKE("get_symlinks")),
	temporarySymlinks: () => typedError<{ [key in string]: Symlink }, string>(__TAURI_INVOKE("temporary_symlinks")),
	create: (link: SymlinkCreateRequest) => typedError<Symlink, string>(__TAURI_INVOKE("create", { link })),
	remove: (link: Symlink) => typedError<null, string>(__TAURI_INVOKE("remove", { link })),
	toggle: (link: Symlink) => typedError<Symlink, string>(__TAURI_INVOKE("toggle", { link })),
	update: (old: Symlink, updated: Symlink) => typedError<Symlink, string>(__TAURI_INVOKE("update", { old, updated })),
	openUrl: (url: string) => typedError<null, string>(__TAURI_INVOKE("open_url", { url })),
	openPath: (path: string) => typedError<null, string>(__TAURI_INVOKE("open_path", { path })),
	checkLauncherUpdates: (includePrerelease: boolean) => typedError<UpdateData, string>(__TAURI_INVOKE("check_launcher_updates", { includePrerelease })),
	installLauncherUpdate: (includePrerelease: boolean) => typedError<null, string>(__TAURI_INVOKE("install_launcher_update", { includePrerelease })),
	downloadLauncherUpdate: (includePrerelease: boolean) => typedError<string, string>(__TAURI_INVOKE("download_launcher_update", { includePrerelease })),
	applyDownloadedUpdate: () => typedError<null, string>(__TAURI_INVOKE("apply_downloaded_update")),
	getCurrentVersion: () => typedError<string, string>(__TAURI_INVOKE("get_current_version")),
	loadWorlds: () => typedError<WorldSummary[], string>(__TAURI_INVOKE("load_worlds")),
	loadWorld: (path: string) => typedError<World, string>(__TAURI_INVOKE("load_world", { path })),
	loadWorldLevel: (path: string) => typedError<WorldLevel, string>(__TAURI_INVOKE("load_world_level", { path })),
	loadWorldPlayers: (path: string) => typedError<WorldPlayer[], string>(__TAURI_INVOKE("load_world_players", { path })),
	loadWorldPlayer: (path: string, uuid: string) => typedError<WorldPlayer, string>(__TAURI_INVOKE("load_world_player", { path, uuid })),
	loadWorldDimensions: (path: string) => typedError<WorldDimension[], string>(__TAURI_INVOKE("load_world_dimensions", { path })),
	loadWorldRegionStorage: (path: string) => typedError<WorldRegionStorage[], string>(__TAURI_INVOKE("load_world_region_storage", { path })),
	loadWorldDatapacks: (path: string) => typedError<WorldDatapack[], string>(__TAURI_INVOKE("load_world_datapacks", { path })),
	loadWorldNbt: (path: string) => typedError<NbtValue, string>(__TAURI_INVOKE("load_world_nbt", { path })),
};

/* Types */
export type AdvancedSettings = {
	enable_advanced_features?: boolean,
	enable_nightly_updates?: boolean,
	developer_mode?: boolean,
	extra?: { [key in string]: string },
};

export type AppearanceSettings = {
	theme?: Theme,
	language?: Language,
	icon_template?: string | null,
	custom_icon_templates?: IconTemplate[],
	selected_css_theme?: Theme | null,
	sound_settings?: SoundSettings,
};

export type CategorizedLauncherSettings = {
	general?: GeneralSettings,
	appearance?: AppearanceSettings,
	content?: ContentSettings,
	logging?: LoggingSettings,
	network?: NetworkSettings,
	advanced?: AdvancedSettings,
	misc?: MiscSettings,
};

export type ClientSide = "required" | "optional" | "unsupported";

export type ContentSettings = {
	allow_adult_content?: boolean,
	allow_ads?: boolean,
	enable_recommendations?: boolean,
	enable_notifications?: boolean,
};

export type DependencyType = "required" | "optional" | "incompatible" | "embedded" | "other";

export type DeviceCodeResponse = {
	device_code: string,
	user_code: string,
	verification_uri: string,
	expires_in: number,
	interval: number,
};

export type Facet = {
	field: FacetField,
	operator: FacetOperator,
	value: string,
};

export type FacetField = "project_type" | 
/**  Categories also contains loaders: "fabric", "forge", "quilt", "neo-forge", etc. */
"categories" | "version" | "client_side" | "server_side" | "open_source" | "title" | "author" | "follows" | "project_id" | "license" | "downloads" | "color" | "created_timestamp" | "modified_timestamp" | "date_created" | "date_modified";

export type FacetGroup = {
	facets: Facet[],
};

export type FacetOperator = "eq" | "not_eq" | "greater" | "greater_eq" | "less" | "less_eq";

export type FileType = "required-resource-pack" | "optional-resource-pack" | "sources-jar" | "dev-jar" | "javadoc-jar" | "signature" | "unknown";

export type GeneralSettings = {
	java_path?: string | null,
	game_directory?: string | null,
	on_game_close?: OnGameAction,
	on_game_crash?: OnGameAction,
	on_game_launch?: OnGameAction,
	update_mode?: UpdateMode,
	update_detection?: UpdateDetection,
	update_notification_style?: UpdateNotificationStyle,
};

export type IconData = { icon: string; type: IconType } | string;

export type IconTemplate = {
	id: string,
	name: string,
	type: IconTemplateType,
	default_icon_type: IconType,
	description: string | null,
	author: string[],
	version: string | null,
	fallback_icon: string,
	icons: { [key in string]: IconData },
	preview_svg: string | null,
	created_at: number | null,
	updated_at: number | null,
};

export type IconTemplateType = "builtin" | "custom";

export type IconType = "emoji" | "svg" | "css_class";

export type KableAccount = {
	access_token: string,
	access_token_expires_at: string,
	/**  AES-encrypted refresh token for "persistent" accounts. */
	encrypted_refresh_token: string | null,
	avatar: string,
	eligible_for_free_trials: boolean,
	eligible_for_migration: boolean,
	franchise_inventory_id: string,
	has_multiple_profiles: boolean,
	in_forced_migration: boolean,
	legacy: boolean,
	license_product_ids: string[],
	/**  This is usually the same as the user's UUID but for correctness use the Minecraft Profile's ID! */
	local_id: string,
	minecraft_profile: KableMinecraftProfile,
	persistent: boolean,
	remote_id: string,
	type: string,
	user_properties: null[],
	username: string,
};

export type KableMinecraftProfile = {
	id: string,
	name: string,
	requires_profile_name_change: boolean,
	requires_skin_change: boolean,
};

/**
 *  Represents a Kable Minecraft Profile, which contains more information than a standard Minecraft Profile:
 *  ```rs
 *  pub struct KableProfile {
 *      pub id: String,
 *      pub name: String,
 *      pub icon: Option<String>,
 *      pub version: ProfileVersion,
 *      pub created: String,
 *      pub last_used: String,
 *      pub java_args: Vec<String>,
 *      pub dedicated_mods_folder: Option<String>,
 *      pub dedicated_resource_pack_folder: Option<String>,
 *      pub dedicated_shaders_folder: Option<String>,
 *      pub dedicated_config_folder: Option<String>,
 *      pub favorite: bool,
 *      pub total_time_played_ms: u32,
 *      pub parameters_map: HashMap<String, String>,
 *      pub description: Option<String>,
 *      pub times_launched: u32,
 *      #[serde(default)]
 *      pub enable_pack_merging: bool,
 *      #[serde(default)]
 *      pub pack_order: Vec<String>,
 *      #[serde(default)]
 *      pub merged_packs: Vec<String>,
 *  }
 *  ```
 */
export type KableProfile = {
	id: string,
	version: ProfileVersion,
	metadata: KableProfileMetadata,
	settings: KableProfileSettings,
};

export type KableProfileMetadata = {
	name: string,
	icon: string | null,
	created: string,
	last_used: string,
	favorite: boolean,
	total_time_played_ms: number,
	description: string | null,
	times_launched: number,
};

export type KableProfileSettings = {
	parameters_map: { [key in string]: string },
	java_args: string[],
	enable_pack_merging?: boolean,
	/**  Lists the packs, by filename relative to the resource pack folder, in the order they are "stacked" when merging, if enabled. */
	pack_order?: string[],
	/**  Lists the packs, by filename relative to the resource pack folder, which should be merged into a single pack before we launch the game */
	merged_packs?: string[],
	/**  lists of enabled/disabled content/projects, the ToggleableContent lists contain filenames relative to the respective folders, e.g. "mods/forge-1.19.2-43.2.0.jar" or "resourcepacks/faithful-1.19.zip" */
	mods: Projects,
	resourcepacks: Projects,
	shaders: Projects,
};

/**  Represents a project in a profile's dedicated mods folder, including its metadata and whether it is enabled or disabled */
export type KableProject = {
	/**  The project itself, containing all of its metadata */
	project: Project,
	/**  Should match a ProjectVersion.id and indicate what version of the mod is installed in the profile's dedicated mods folder */
	version_id: string,
	/**  The filename of the mod jar file in the profile's dedicated mods folder, should match a ProjectVersion.files.filename, and is used to locate the mod jar file in the profile's dedicated mods folder */
	filename: string,
};

export type Language = "english";

export type LaunchResult = {
	pid: number,
	runtime_id: string,
	command: string,
};

export type LoaderKind = "vanilla" | "fabric" | "iris_fabric" | "forge" | "neo_forge" | "quilt";

export type LoggingSettings = {
	enabled?: boolean,
	persistent?: boolean,
	compression?: boolean,
	retention_days?: number,
	max_file_size_mb?: number,
	frontend_batch_size?: number,
	frontend_batch_interval_ms?: number,
	frontend_max_per_second?: number,
	max_memory_logs?: number,
	dedupe_enabled?: boolean,
	dedupe_window_size?: number,
};

export type MicrosoftToken = {
	access_token: string,
	expires_at: string,
	/**  Raw refresh token from device code flow. Should be encrypted if stored persistently!! */
	refresh_token: string | null,
};

export type MiscSettings = {
	/**  I keep this mostly undocumented because it is open-source and I don't want to spoil the fun features (: */
	enable_fun?: boolean,
};

export type ModrinthResults = {
	/**  The list of results */
	hits: Project[],
	/**  The number of results that were skipped by the query */
	offset: number,
	/**  The number of results that were returned by the query */
	limit: number,
	/**  The total number of results that match the query */
	total_hits: number,
};

/**  The monetization status of the project */
export type MonetizationStatus = "monetized" | "demonetized" | "force-demonetized" | "other";

export type NbtEntry = {
	name: string,
	value: NbtValue,
};

export type NbtValue = { type: "Byte"; value: number } | { type: "Short"; value: number } | { type: "Int"; value: number } | { type: "Long"; value: string } | { type: "Float"; value: number | null } | { type: "Double"; value: number | null } | { type: "ByteArray"; value: number[] } | { type: "String"; value: string } | { type: "List"; value: NbtValue[] } | { type: "Compound"; value: NbtEntry[] } | { type: "IntArray"; value: number[] } | { type: "LongArray"; value: string[] };

export type NetworkSettings = {
	max_download_threads?: number | null,
	max_download_speed_kbps?: number | null,
	max_requests_per_second?: number | null,
};

export type OnGameAction = "ask" | "exit" | "minimize" | "minimize_to_tray" | "nothing" | 
/**  Opens a specific page by name, e.g. "home", "logs", etc. */
{ open: string } | "restart";

export type ProfileVersion = {
	/**  Raw version ID from the profile, e.g. "1.19.2-forge-43.2.0" */
	id: string,
	display_name: string,
	/**  Vanilla, Fabric, Forge, NeoForge, Quilt, etc. */
	loader: LoaderKind,
	/**  Optional Minecraft version, e.g. "1.19.2", note that since 2026 minecraft versioning is <year>.<drop>.<patch> (e.g. 26.2.1) */
	minecraft_version: string | null,
	/**  Optional loader version, e.g. "43.2.0" for forge or "0.14.19" for fabric */
	loader_version: string | null,
	/**  Release, Snapshot, OldBeta, OldAlpha */
	version_type: ProfileVersionType | null,
	/**  Whether this version is marked as stable in the profile, note that this is not necessarily the same as version_type == Release */
	stable: boolean | null,
	/**  Extra metadata that may be present from the version manifest */
	release_time: string | null,
	updated_time: string | null,
	url: string | null,
	sha1: string | null,
	compliance_level: number | null,
	recommended: boolean | null,
};

export type ProfileVersionType = "release" | "snapshot" | "old_beta" | "old_alpha";

export type Project = {
	/**  The slug of a project, used for vanity URLs. Regex: ```^[\\w!@$()`.+,\"\\-']{3,64}$``` */
	slug: string,
	/**  The title or name of the project */
	title: string,
	/**  A short description of the project */
	description: string,
	/**  A list of the categories that the project has */
	categories: string[] | null,
	/**  The client side support of the project */
	client_side: ClientSide,
	/**  The server side support of the project */
	server_side: ServerSide,
	/**  The project type of the project */
	project_type: ProjectType,
	/**  The total number of downloads of the project */
	downloads: number,
	/**  The URL of the project's icon */
	icon_url: string | null,
	/**  The RGB color of the project, automatically generated from the project icon */
	color: number | null,
	/**  The ID of the moderation thread associated with this project */
	thread_id: string | null,
	monetization_status: MonetizationStatus | null,
	/**  The ID of the project */
	project_id: string,
	/**  The username of the project's author */
	author: string,
	/**  A list of the categories that the project has which are not secondary */
	display_categories: string[] | null,
	/**  A list of the minecraft versions supported by the project */
	versions: ProjectVersion[],
	/**  The total number of users following the project */
	follows: number,
	/**  The date the project was added to search */
	date_created: string,
	/**  The date the project was last modified */
	date_modified: string,
	/**  The latest version of minecraft that this project supports */
	latest_version: string | null,
	/**  The SPDX license ID of a project */
	license: string,
	/**  All gallery images attached to the project */
	gallery: string[] | null,
	/**  The featured gallery image of the project */
	featured_gallery: string | null,
};

export type ProjectSearch = {
	query: string | null,
	facets: FacetGroup[],
	index: SearchIndex | null,
	offset: number | null,
	limit: number | null,
};

/**  The project type of the project */
export type ProjectType = "mod" | "modpack" | "resourcepack" | "shader" | "plugin" | "datapack" | "minecraft-java-server" | "other";

export type ProjectVersion = {
	/**  The name of this version */
	name: string,
	/**  The version number. Ideally will follow semantic versioning */
	version_number: string,
	/**  The changelog for this version */
	changelog: string | null,
	/**  A list of specific versions of projects that this version depends on */
	dependencies: VersionDependency[] | null,
	/**  A list of versions of Minecraft that this version supports */
	game_versions: string[],
	/**  The release channel for this version */
	version_type: VersionType,
	/**  The mod loaders that this version supports */
	loaders: string[],
	/**  Whether the version is featured or not */
	featured: boolean,
	status: Status | null,
	requested_status: RequestedStatus | null,
	/**  The ID of the version, encoded as a base62 string */
	id: string,
	/**  The ID of the project this version is for */
	project_id: string,
	/**  The ID of the author who published this version */
	author_id: string,
	date_published: string,
	/**  The number of times this version has been downloaded */
	downloads: number,
	/**  A link to the changelog for this version. Always null, only kept for legacy compatibility. */
	changelog_url: string | null,
	/**  A list of files available for download for this version */
	files: VersionFile[],
};

export type Projects = {
	enabled: string[],
	disabled: string[],
};

export type RequestedStatus = "listed" | "archived" | "draft" | "unlisted" | "other";

export type SearchIndex = "relevance" | "downloads" | "follows" | "newest" | "updated";

/**  The server side support of the project */
export type ServerSide = "required" | "optional" | "unsupported";

export type SoundSettings = {
	enabled?: boolean,
	music_enabled?: boolean,
	master_volume?: number,
	sound_volume?: number,
	music_volume?: number,
	selected_soundpack?: string,
};

export type SoundpackMetadata = {
	id: string,
	name: string,
	description: string | null,
	author: string | null,
	version: string | null,
	file_path: string | null,
};

export type Status = "listed" | "archived" | "draft" | "unlisted" | "scheduled" | "unknown";

export type Symlink = {
	id: string,
	source: string,
	destination: string,
	is_temporary: boolean,
	enabled: boolean,
	from_launcher: boolean,
};

export type SymlinkCreateRequest = {
	source: string,
	destination: string,
};

export type Theme = "light" | "dark" | "system" | 
/**  Custom theme, specified by a path/name to a CSS file */
{ custom: string };

export type UpdateData = {
	version: string,
	date: string | null,
	body: string,
	current_version: string,
};

/**  This determines WHEN to check for updates */
export type UpdateDetection = "on_startup" | "on_close" | 
/**  Checks for updates every N seconds */
{ periodically: number } | "manual";

export type UpdateMap = {
	kable_project: KableProject,
	update: Project | null,
};

/**  This determines HOW, once checked, to perform the update. */
export type UpdateMode = 
/**  After a check the user gets prompted to confirm, skip/cancel or only download and wait for restart */
"on_confirm" | 
/**  Download + install automatically, without asking the user */
"automatic" | 
/**  No checks, no prompts, nothing. Users have to go to settings and do everything manually. */
"manual";

export type UpdateNotificationStyle = "notification" | "modal";

export type VersionDependency = {
	/**  The ID of the version that this version depends on */
	version_id: string | null,
	/**  The ID of the project that this version depends on */
	project_id: string | null,
	/**  The file name of the dependency, mostly used for showing external dependencies on modpacks */
	file_name: string | null,
	/**  The type of dependency that this version has */
	dependency_type: DependencyType,
};

export type VersionFile = {
	hashes: VersionFileHashes,
	/**  A direct link to the file */
	url: string,
	/**  The name of the file */
	filename: string,
	/**  Whether this file is the primary one for its version. Only a maximum of one file per version will have this set to true. If there are not any primary files, it can be inferred that the first file is the primary one. */
	primary: boolean,
	/**  The size of the file in bytes */
	size: number,
	/**  The type of the additional file, used mainly for adding resource packs to datapacks */
	file_type: FileType | null,
};

export type VersionFileHashes = {
	sha512: string | null,
	sha1: string | null,
};

/**  The release channel for this version */
export type VersionType = "release" | "beta" | "alpha" | 
/**  This one is used when converting String to ProjectVersion as they lack a lot of info but the alternative is dropping all version info on converting ProjectResults... */
"incomplete";

export type Versions = ProfileVersion[];

export type World = {
	id: string,
	name: string,
	path: string,
	icon: string | null,
	last_modified: string | null,
	level: WorldLevel | null,
	players: WorldPlayer[],
	dimensions: WorldDimension[],
	datapacks: WorldDatapack[],
	region_storage: WorldRegionStorage[],
	advancements: WorldAdvancement[],
	statistics: WorldPlayerStatistics[],
};

export type WorldAdvancement = {
	id: string,
	player_uuid: string,
	done: boolean,
	criteria: WorldAdvancementProgress[],
};

export type WorldAdvancementProgress = {
	id: string,
	achieved_at: string | null,
	raw: NbtValue | null,
};

export type WorldBorder = {
	center_x: number | null,
	center_z: number | null,
	size: number | null,
	damage_per_block: number | null,
	safe_zone: number | null,
	warning_blocks: number | null,
	warning_time: number | null,
	lerp_target: number | null,
	lerp_time: string | null,
};

export type WorldChunk = {
	x: number,
	z: number,
	region_x: number,
	region_z: number,
	sector_offset: number,
	sector_count: number,
	timestamp: string | null,
	compression: WorldChunkCompression | null,
	compressed_size: number | null,
	data: number[] | null,
};

export type WorldChunkCompression = "gzip" | "zlib" | "uncompressed" | "lz4" | { custom: number };

export type WorldDatapack = {
	id: string,
	name: string | null,
	description: string | null,
	pack_format: number | null,
	min_format: number | null,
	max_format: number | null,
	enabled: boolean,
	path: string,
};

export type WorldDifficulty = "peaceful" | "easy" | "normal" | "hard" | "unknown";

export type WorldDimension = {
	id: string,
	kind: WorldDimensionKind,
	path: string,
	region_storage: WorldRegionStorage | null,
	chunk_count: string,
	region_count: string,
};

export type WorldDimensionKind = "overworld" | "nether" | "end" | "custom" | "unknown";

export type WorldGameMode = "survival" | "creative" | "adventure" | "spectator" | "unknown";

export type WorldGameRule = {
	name: string,
	value: string,
};

export type WorldInventoryItem = {
	slot: number,
	item_id: string,
	count: number,
	nbt: NbtValue | null,
};

export type WorldLevel = {
	data_version: number | null,
	version: WorldVersion | null,
	level_name: string | null,
	game_mode: WorldGameMode | null,
	difficulty: WorldDifficulty | null,
	hardcore: boolean | null,
	allow_commands: boolean | null,
	seed: string | null,
	time: WorldTime | null,
	spawn: WorldSpawn | null,
	weather: WorldWeather | null,
	world_border: WorldBorder | null,
	game_rules: WorldGameRule[],
	nbt: NbtValue | null,
};

export type WorldPlayer = {
	uuid: string,
	path: string,
	name: string | null,
	dimension: string | null,
	position: WorldPosition | null,
	rotation: WorldRotation | null,
	health: number | null,
	food_level: number | null,
	food_saturation: number | null,
	experience_level: number | null,
	experience: number | null,
	total_experience: number | null,
	game_mode: WorldGameMode | null,
	inventory: WorldInventoryItem[],
	ender_items: NbtValue | null,
	nbt: NbtValue | null,
};

export type WorldPlayerStatistics = {
	uuid: string,
	path: string,
	statistics: WorldStatistic[],
};

export type WorldPosition = {
	x: number | null,
	y: number | null,
	z: number | null,
};

export type WorldRegion = {
	x: number,
	z: number,
	path: string,
	size: string,
	chunk_count: number,
	chunks: WorldChunk[],
};

export type WorldRegionStorage = {
	path: string,
	region_count: string,
	chunk_count: string,
	total_size: string,
	regions: WorldRegion[],
};

export type WorldRotation = {
	yaw: number | null,
	pitch: number | null,
};

export type WorldSpawn = {
	x: number,
	y: number,
	z: number,
	angle: number | null,
};

export type WorldStatistic = {
	category: string,
	name: string,
	value: string,
};

export type WorldSummary = {
	id: string,
	name: string,
	path: string,
	icon: string | null,
	last_modified: string | null,
};

export type WorldTime = {
	game_time: string | null,
	day_time: string | null,
};

export type WorldVersion = {
	name: string | null,
	id: number | null,
	snapshot: boolean | null,
};

export type WorldWeather = {
	raining: boolean | null,
	rain_time: number | null,
	thundering: boolean | null,
	thunder_time: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

