// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	startAuthentication: () => typedError<DeviceCodeResponse, string>(__TAURI_INVOKE("start_authentication")),
	pollAuthentication: (deviceCode: string) => typedError<MicrosoftToken, string>(__TAURI_INVOKE("poll_authentication", { deviceCode })),
	listAccounts: () => typedError<LauncherAccount[], string>(__TAURI_INVOKE("list_accounts")),
	addAccount: (account: LauncherAccount) => typedError<null, string>(__TAURI_INVOKE("add_account", { account })),
	removeAccount: (account: LauncherAccount) => typedError<LauncherAccount[], string>(__TAURI_INVOKE("remove_account", { account })),
	setActiveAccount: (account: LauncherAccount) => typedError<null, string>(__TAURI_INVOKE("set_active_account", { account })),
	getActiveAccount: () => typedError<{
	access_token: string,
	access_token_expires_at: string,
	/**  AES-encrypted refresh token for "persistent" accounts. */
	encrypted_refresh_token: string | null,
	avatar: string,
	eligible_for_free_trials: boolean,
	eligible_for_migration: boolean,
	franchise_inventory_id: string,
	has_multiple_profiles: boolean,
	in_forced_migration: boolean,
	legacy: boolean,
	license_product_ids: string[],
	/**  This is usually the same as the user's UUID but for correctness use the Minecraft Profile's ID! */
	local_id: string,
	minecraft_profile: MinecraftProfile,
	persistent: boolean,
	remote_id: string,
	type: string,
	user_properties: null[],
	username: string,
} | null, string>(__TAURI_INVOKE("get_active_account")),
	getCustomIconTemplates: () => typedError<CustomIconTemplate[], string>(__TAURI_INVOKE("get_custom_icon_templates")),
	saveCustomIconTemplate: (template: CustomIconTemplate) => typedError<string, string>(__TAURI_INVOKE("save_custom_icon_template", { template })),
	deleteCustomIconTemplate: (templateName: string) => typedError<null, string>(__TAURI_INVOKE("delete_custom_icon_template", { templateName })),
	openIconsDirectory: () => typedError<null, string>(__TAURI_INVOKE("open_icons_directory")),
	resolveImagePath: (key: string) => typedError<string, string>(__TAURI_INVOKE("resolve_image_path", { key })),
	launchGame: (profile: KableProfile) => typedError<LaunchResult, string>(__TAURI_INVOKE("launch_game", { profile })),
	autoDetectJava: () => typedError<string, string>(__TAURI_INVOKE("auto_detect_java")),
	getJavaPath: (javaPath: string | null) => typedError<string, string>(__TAURI_INVOKE("get_java_path", { javaPath })),
	getProfiles: () => typedError<KableProfile[], string>(__TAURI_INVOKE("get_profiles")),
	getProfile: (id: string) => typedError<KableProfile, string>(__TAURI_INVOKE("get_profile", { id })),
	modifyProfile: (oldProfile: KableProfile, newProfile: KableProfile) => typedError<KableProfile, string>(__TAURI_INVOKE("modify_profile", { oldProfile, newProfile })),
	deleteProfile: (id: string) => typedError<null, string>(__TAURI_INVOKE("delete_profile", { id })),
	getVersions: () => typedError<Versions, string>(__TAURI_INVOKE("get_versions")),
	getSettings: () => typedError<CategorizedLauncherSettings, string>(__TAURI_INVOKE("get_settings")),
	setSettings: (settings: CategorizedLauncherSettings) => typedError<null, string>(__TAURI_INVOKE("set_settings", { settings })),
	listSoundpacks: () => typedError<string[], string>(__TAURI_INVOKE("list_soundpacks")),
	getSoundpackMetadata: (pack: string) => typedError<SoundpackMetadata, string>(__TAURI_INVOKE("get_soundpack_metadata", { pack })),
	loadSoundpackFile: (pack: string, file: string) => typedError<number[], string>(__TAURI_INVOKE("load_soundpack_file", { pack, file })),
	importSoundpackZip: (path: string) => typedError<string, string>(__TAURI_INVOKE("import_soundpack_zip", { path })),
	getSoundsDirectoryPath: () => typedError<string, string>(__TAURI_INVOKE("get_sounds_directory_path")),
	openSoundsDirectory: () => typedError<null, string>(__TAURI_INVOKE("open_sounds_directory")),
	getSymlinks: () => typedError<SymlinkView[], string>(__TAURI_INVOKE("get_symlinks")),
	createSymlink: (request: CreateSymlinkRequest) => typedError<null, string>(__TAURI_INVOKE("create_symlink", { request })),
	deleteSymlink: (id: string) => typedError<null, string>(__TAURI_INVOKE("delete_symlink", { id })),
	enableSymlink: (id: string) => typedError<null, string>(__TAURI_INVOKE("enable_symlink", { id })),
	disableSymlink: (id: string) => typedError<null, string>(__TAURI_INVOKE("disable_symlink", { id })),
	checkForUpdates: (includePrerelease: boolean) => typedError<{
	version: string,
	date: string | null,
	body: string,
	current_version: string,
} | null, string>(__TAURI_INVOKE("check_for_updates", { includePrerelease })),
	installUpdate: (includePrerelease: boolean) => typedError<null, string>(__TAURI_INVOKE("install_update", { includePrerelease })),
	downloadUpdate: (includePrerelease: boolean) => typedError<string, string>(__TAURI_INVOKE("download_update", { includePrerelease })),
	applyDownloadedUpdate: () => typedError<null, string>(__TAURI_INVOKE("apply_downloaded_update")),
	getCurrentVersion: () => typedError<string, string>(__TAURI_INVOKE("get_current_version")),
};

/* Types */
export type AdvancedSettings = {
	developer_mode?: boolean,
	extra: { [key in string]: string },
};

export type AppearanceSettings = {
	selected_css_theme?: string,
};

export type CategorizedLauncherSettings = {
	general?: GeneralSettings,
	appearance?: AppearanceSettings,
	logging?: LoggingSettings,
	network?: NetworkSettings,
	content?: ContentSettings,
	advanced?: AdvancedSettings,
	misc?: MiscSettings,
};

export type ContentSettings = {
	allow_adult_content?: boolean,
};

export type CreateSymlinkRequest = {
	source: string,
	destination: string,
	installation_id: string | null,
	category: SymlinkCategory,
	source_type: SymlinkSource,
	enabled: boolean,
};

export type CustomIconTemplate = {
	id: string,
	name: string,
	description: string | null,
	svg_data: string,
	preview_svg: string | null,
	created_at: number | null,
	updated_at: number | null,
};

export type DeviceCodeResponse = {
	device_code: string,
	user_code: string,
	verification_uri: string,
	expires_in: number,
	interval: number,
};

export type GeneralSettings = {
	java_path?: string | null,
	game_directory?: string | null,
	on_game_close?: string,
	on_game_crash?: string,
	on_game_launch?: string,
	auto_update_launcher?: boolean,
	show_ads?: boolean,
	update_mode?: string,
	update_notification_style?: string,
};

export type KableProfile = {
	id: string,
	name: string,
	icon: string | null,
	version: ProfileVersion,
	created: string,
	last_used: string,
	java_args: string[],
	dedicated_mods_folder: string | null,
	dedicated_resource_pack_folder: string | null,
	dedicated_shaders_folder: string | null,
	dedicated_config_folder: string | null,
	favorite: boolean,
	total_time_played_ms: number,
	parameters_map: { [key in string]: string },
	description: string | null,
	times_launched: number,
	enable_pack_merging?: boolean,
	pack_order?: string[],
	merged_packs?: string[],
};

export type LaunchResult = {
	pid: number,
	runtime_id: string,
	command: string,
};

export type LauncherAccount = {
	access_token: string,
	access_token_expires_at: string,
	/**  AES-encrypted refresh token for "persistent" accounts. */
	encrypted_refresh_token: string | null,
	avatar: string,
	eligible_for_free_trials: boolean,
	eligible_for_migration: boolean,
	franchise_inventory_id: string,
	has_multiple_profiles: boolean,
	in_forced_migration: boolean,
	legacy: boolean,
	license_product_ids: string[],
	/**  This is usually the same as the user's UUID but for correctness use the Minecraft Profile's ID! */
	local_id: string,
	minecraft_profile: MinecraftProfile,
	persistent: boolean,
	remote_id: string,
	type: string,
	user_properties: null[],
	username: string,
};

export type LoaderKind = "vanilla" | "fabric" | "iris_fabric" | "forge" | "neo_forge" | "quilt";

export type LoggingSettings = {
	enabled: boolean,
	persistent: boolean,
	compression: boolean,
	retention_days: number,
	max_file_size_mb: number,
	frontend_batch_size: number,
	frontend_batch_interval_ms: number,
	frontend_max_per_second: number,
	max_memory_logs: number,
	dedupe_enabled: boolean,
	dedupe_window_size: number,
};

export type MicrosoftToken = {
	access_token: string,
	expires_at: string,
	/**  Raw refresh token from device code flow. Should be encrypted if stored persistently!! */
	refresh_token: string | null,
};

export type MinecraftProfile = {
	id: string,
	name: string,
	requires_profile_name_change: boolean,
	requires_skin_change: boolean,
};

export type MiscSettings = {
	check_for_updates_on_start?: boolean,
};

export type NetworkSettings = {
	use_proxy?: boolean,
};

export type ProfileVersion = {
	/**  Raw version ID from the profile, e.g. "1.19.2-forge-43.2.0" */
	id: string,
	display_name: string,
	/**  Vanilla, Fabric, Forge, NeoForge, Quilt, etc. */
	loader: LoaderKind,
	/**  Optional Minecraft version, e.g. "1.19.2", note that since 2026 minecraft versioning is <year>.<drop>.<patch> (e.g. 26.2.1) */
	minecraft_version: string | null,
	/**  Optional loader version, e.g. "43.2.0" for forge or "0.14.19" for fabric */
	loader_version: string | null,
	/**  Release, Snapshot, OldBeta, OldAlpha */
	version_type: VersionType | null,
	/**  Whether this version is marked as stable in the profile, note that this is not necessarily the same as version_type == Release */
	stable: boolean | null,
	/**  Extra metadata that may be present from the version manifest */
	release_time: string | null,
	updated_time: string | null,
	url: string | null,
	sha1: string | null,
	compliance_level: number | null,
	recommended: boolean | null,
};

export type SoundpackMetadata = {
	id: string,
	name: string,
	description: string | null,
	author: string | null,
	version: string | null,
	file_path: string | null,
};

export type SymlinkCategory = "resource_pack" | "shader_pack" | "world" | "mod" | "custom";

export type SymlinkKind = "file" | "directory";

export type SymlinkSource = "managed" | "custom";

export type SymlinkState = "enabled" | "disabled" | "missing_target" | "missing_link" | "broken";

export type SymlinkView = {
	id: string,
	source: string,
	destination: string,
	installation_id: string | null,
	category: SymlinkCategory,
	kind: SymlinkKind,
	source_type: SymlinkSource,
	state: SymlinkState,
	source_exists: boolean,
	link_exists: boolean,
};

export type UpdateData = {
	version: string,
	date: string | null,
	body: string,
	current_version: string,
};

export type VersionType = "release" | "snapshot" | "old_beta" | "old_alpha";

export type Versions = ProfileVersion[];

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

